/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import datos.Rol;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class EditarRol extends javax.swing.JFrame {

    /**
     * Creates new form AgregarUser
     */
    public EditarRol(){
        
    }
    
    public EditarRol(String idRol) throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Editar Rol");
        
        //DESHABILITAR BOTON CERRAR
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
          public void windowClosing(WindowEvent e) {
            JOptionPane.showMessageDialog(null, "Usar el boton SALIR del menu inicio!", "AVISO",JOptionPane.INFORMATION_MESSAGE);
          }
        });           
        
        //Llamar metodo verRol 
        try{
        Rol role = new Rol();
        ArrayList<Rol> rol = (ArrayList<Rol>) role.verRol(idRol);
       
        //Llenar formulario
        for (int i = 0; i < rol.size(); i++){
            txtId.setText(Integer.toString(rol.get(i).id));
            txtRol.setText(rol.get(i).rol);
            txtNumeroPrestamos.setText(Integer.toString(rol.get(i).numero_prestamos));
            txtDiasPrestamo.setText(Integer.toString(rol.get(i).dias_prestamo));
        }}
        catch(SQLException ex){
            Logger.getLogger(EditarRol.class.getName()).log(Level.SEVERE, null, ex); 
        }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        txtUsuario = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtMora = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        txtNumeroPrestamos = new javax.swing.JTextField();
        lblNickname = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txtDiasPrestamo = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtRol = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator6.setForeground(new java.awt.Color(102, 0, 204));
        jSeparator6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 183, -1));

        txtUsuario.setBackground(new java.awt.Color(0, 0, 51));
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setAlignmentX(0.8F);
        txtUsuario.setBorder(null);
        txtUsuario.setMargin(new java.awt.Insets(5, 15, 5, 5));
        txtUsuario.setMinimumSize(new java.awt.Dimension(5, 20));
        txtUsuario.setName("txtUsuario"); // NOI18N
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 107, 5, 19));

        lblNombre.setBackground(new java.awt.Color(0, 0, 51));
        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("Rol:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(0, 0, 51));
        txtId.setForeground(new java.awt.Color(204, 204, 204));
        txtId.setToolTipText("");
        txtId.setBorder(null);
        txtId.setCaretColor(new java.awt.Color(255, 255, 255));
        txtId.setEnabled(false);
        txtId.setMargin(new java.awt.Insets(5, 15, 5, 5));
        txtId.setMinimumSize(new java.awt.Dimension(5, 20));
        txtId.setName("txtUsuario"); // NOI18N
        txtId.setNextFocusableComponent(txtMora);
        txtId.setSelectedTextColor(new java.awt.Color(0, 51, 153));
        txtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdMousePressed(evt);
            }
        });
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 40, 19));

        txtMora.setBackground(new java.awt.Color(0, 0, 51));
        txtMora.setForeground(new java.awt.Color(204, 204, 204));
        txtMora.setAlignmentX(0.8F);
        txtMora.setBorder(null);
        txtMora.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMora.setMargin(new java.awt.Insets(5, 15, 5, 5));
        txtMora.setMinimumSize(new java.awt.Dimension(5, 20));
        txtMora.setName("txtMora"); // NOI18N
        txtMora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMoraMousePressed(evt);
            }
        });
        txtMora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoraActionPerformed(evt);
            }
        });
        jPanel1.add(txtMora, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 183, 19));

        jSeparator8.setForeground(new java.awt.Color(102, 0, 204));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 183, -1));

        txtNumeroPrestamos.setBackground(new java.awt.Color(0, 0, 51));
        txtNumeroPrestamos.setForeground(new java.awt.Color(204, 204, 204));
        txtNumeroPrestamos.setText("Ingrese numero maximo de prestamos");
        txtNumeroPrestamos.setAlignmentX(0.8F);
        txtNumeroPrestamos.setBorder(null);
        txtNumeroPrestamos.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNumeroPrestamos.setMargin(new java.awt.Insets(5, 15, 5, 5));
        txtNumeroPrestamos.setMinimumSize(new java.awt.Dimension(5, 20));
        txtNumeroPrestamos.setName("txtNumeroPrestamos"); // NOI18N
        txtNumeroPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroPrestamosMousePressed(evt);
            }
        });
        txtNumeroPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroPrestamosActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 183, 19));

        lblNickname.setBackground(new java.awt.Color(0, 0, 51));
        lblNickname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNickname.setForeground(new java.awt.Color(204, 204, 204));
        lblNickname.setText("Número Máximo de Prestamos:");
        jPanel1.add(lblNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(102, 0, 204));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 183, -1));

        txtDiasPrestamo.setBackground(new java.awt.Color(0, 0, 51));
        txtDiasPrestamo.setForeground(new java.awt.Color(204, 204, 204));
        txtDiasPrestamo.setText("Ingrese maximo de dias");
        txtDiasPrestamo.setAlignmentX(0.8F);
        txtDiasPrestamo.setBorder(null);
        txtDiasPrestamo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDiasPrestamo.setMargin(new java.awt.Insets(5, 15, 5, 5));
        txtDiasPrestamo.setMinimumSize(new java.awt.Dimension(5, 20));
        txtDiasPrestamo.setName("txtDiasPrestamo"); // NOI18N
        txtDiasPrestamo.setNextFocusableComponent(txtMora);
        txtDiasPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDiasPrestamoMousePressed(evt);
            }
        });
        txtDiasPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasPrestamoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiasPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 183, 19));

        lblEmail.setBackground(new java.awt.Color(0, 0, 51));
        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(204, 204, 204));
        lblEmail.setText("Dias Máximo de Prestamos:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        lblNombre2.setBackground(new java.awt.Color(0, 0, 51));
        lblNombre2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre2.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre2.setText("Id:");
        jPanel1.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 255));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setNextFocusableComponent(btnCancelar);
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarMousePressed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 80, 30));

        btnCancelar.setBackground(new java.awt.Color(204, 0, 51));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 80, 30));

        txtRol.setBackground(new java.awt.Color(0, 0, 51));
        txtRol.setForeground(new java.awt.Color(204, 204, 204));
        txtRol.setText("Ingrese nombre de rol");
        txtRol.setAlignmentX(0.8F);
        txtRol.setBorder(null);
        txtRol.setCaretColor(new java.awt.Color(255, 255, 255));
        txtRol.setMargin(new java.awt.Insets(5, 15, 5, 5));
        txtRol.setMinimumSize(new java.awt.Dimension(5, 20));
        txtRol.setName("txtRol"); // NOI18N
        txtRol.setNextFocusableComponent(txtMora);
        txtRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRolMousePressed(evt);
            }
        });
        txtRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRolActionPerformed(evt);
            }
        });
        jPanel1.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 109, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRolActionPerformed

    private void txtRolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRolMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRolMousePressed

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        Ver_Roles ver = null;
        try {
            ver = new Ver_Roles();
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        ver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarMousePressed

    private void btnActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMousePressed
        //Comprobar que los datos no sean nulos ni vaciós
        if(txtRol.getText().equals("Ingrese nombre de rol") || txtNumeroPrestamos.getText().equals("Ingrese numero maximo de prestamos")
            || txtDiasPrestamo.getText().equals("Ingrese maximo de dias")){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO",JOptionPane.INFORMATION_MESSAGE);
            txtRol.requestFocus();
        } else {
            try {
                String id = txtId.getText();
                String rol = txtRol.getText();
                String numero_prestamos = txtNumeroPrestamos.getText();
                String dias_prestamo = txtDiasPrestamo.getText();

                //Llamar metodo para agregar rol a tabla
                Rol newRol = new Rol();
                newRol.actualizarRol(id, rol, numero_prestamos, dias_prestamo);
                this.dispose();
            }
            catch (SQLException ex) {
                java.util.logging.Logger.getLogger(EditarRol.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnActualizarMousePressed

    private void txtDiasPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasPrestamoActionPerformed

    private void txtDiasPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiasPrestamoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasPrestamoMousePressed

    private void txtNumeroPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroPrestamosActionPerformed

    private void txtNumeroPrestamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroPrestamosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroPrestamosMousePressed

    private void txtMoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoraActionPerformed

    private void txtMoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMoraMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoraMousePressed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMousePressed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarRol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JTextField txtDiasPrestamo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMora;
    private javax.swing.JTextField txtNumeroPrestamos;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
