/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ElegirVistaMateriales extends javax.swing.JFrame {

    /**
     * Creates new form Ver_Usuario
     */
    public ElegirVistaMateriales() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Consultar Materiales en sistema");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVerUser = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btncd = new javax.swing.JButton();
        btndvd = new javax.swing.JButton();
        btnrevistas = new javax.swing.JButton();
        btnlibros = new javax.swing.JButton();
        btndocumentos = new javax.swing.JButton();
        btntesis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlVerUser.setBackground(new java.awt.Color(0, 0, 51));
        pnlVerUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atrás");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        pnlVerUser.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 80, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ELEGIR TIPO DE MATERIAL A CONSULTAR");
        pnlVerUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 520, -1));

        btncd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CDDAlogo.png"))); // NOI18N
        btncd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncdActionPerformed(evt);
            }
        });
        pnlVerUser.add(btncd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 130, 90));

        btndvd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DVD_logo.png"))); // NOI18N
        btndvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndvdActionPerformed(evt);
            }
        });
        pnlVerUser.add(btndvd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 160, 90));

        btnrevistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png-transparent-magazine-computer-icons-book-skeptic-icon-magazine-logo-symbol-skeptic.png"))); // NOI18N
        btnrevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrevistasActionPerformed(evt);
            }
        });
        pnlVerUser.add(btnrevistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 120, 90));

        btnlibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.png"))); // NOI18N
        btnlibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibrosActionPerformed(evt);
            }
        });
        pnlVerUser.add(btnlibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, 90));

        btndocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/documentos.png"))); // NOI18N
        btndocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocumentosActionPerformed(evt);
            }
        });
        pnlVerUser.add(btndocumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, 90));

        btntesis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tesis.png"))); // NOI18N
        btntesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntesisActionPerformed(evt);
            }
        });
        pnlVerUser.add(btntesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 120, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TESIS");
        pnlVerUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cd´s");
        pnlVerUser.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DVD");
        pnlVerUser.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("REVISTAS");
        pnlVerUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LIBROS");
        pnlVerUser.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("OBRAS");
        pnlVerUser.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVerUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVerUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        Menu_Materiales mat = new Menu_Materiales();
        mat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MousePressed

    private void rSButtonGradiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente1ActionPerformed

    private void rSButtonGradiente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente4ActionPerformed

    private void rSButtonGradiente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente5ActionPerformed

    private void rSButtonGradiente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente6ActionPerformed

    private void rSButtonGradiente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente7ActionPerformed

    private void rSButtonGradiente8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente8ActionPerformed

    private void rSButtonGradiente9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente9ActionPerformed

    private void rSButtonGradiente10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradiente10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonGradiente10ActionPerformed

    private void btncdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncdActionPerformed
        // TODO add your handling code here:
        VistaCD cd = null;
        try {
            cd = new VistaCD();
        } catch (SQLException ex) {
            Logger.getLogger(ElegirVistaMateriales.class.getName()).log(Level.SEVERE, null, ex);
        }
        cd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncdActionPerformed

    private void btndvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndvdActionPerformed
        // TODO add your handling code here:
        VistaDVD dvd = null;
        try {
            dvd = new VistaDVD();
        } catch (SQLException ex) {
            Logger.getLogger(ElegirVistaMateriales.class.getName()).log(Level.SEVERE, null, ex);
        }
        dvd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndvdActionPerformed

    private void btnrevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrevistasActionPerformed
        // TODO add your handling code here:
        VistaRevistas rev = null;
        try {
            rev = new VistaRevistas();
        } catch (SQLException ex) {
            Logger.getLogger(ElegirVistaMateriales.class.getName()).log(Level.SEVERE, null, ex);
        }
        rev.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnrevistasActionPerformed

    private void btnlibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibrosActionPerformed
        // TODO add your handling code here:
        VistaLibros lib = null;
        try {
            lib = new VistaLibros();
        } catch (SQLException ex) {
            Logger.getLogger(ElegirVistaMateriales.class.getName()).log(Level.SEVERE, null, ex);
        }
        lib.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlibrosActionPerformed

    private void btndocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocumentosActionPerformed
        // TODO add your handling code here:
        VistaObras obr = null;
        try {
            obr = new VistaObras();
        } catch (SQLException ex) {
            Logger.getLogger(ElegirVistaMateriales.class.getName()).log(Level.SEVERE, null, ex);
        }
        obr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndocumentosActionPerformed

    private void btntesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntesisActionPerformed
        // TODO add your handling code here:
        VistaTesis tes = null;
        try {
            tes = new VistaTesis();
        } catch (SQLException ex) {
            Logger.getLogger(ElegirVistaMateriales.class.getName()).log(Level.SEVERE, null, ex);
        }
        tes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btntesisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirVistaMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirVistaMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirVistaMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirVistaMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirVistaMateriales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncd;
    private javax.swing.JButton btndocumentos;
    private javax.swing.JButton btndvd;
    private javax.swing.JButton btnlibros;
    private javax.swing.JButton btnrevistas;
    private javax.swing.JButton btntesis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnlVerUser;
    // End of variables declaration//GEN-END:variables
}
