package vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import datos.Globales;
import datos.Prestamo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Prestar_Material extends javax.swing.JFrame {

    Prestamo prestamos = new Prestamo();

    public Prestar_Material() throws SQLException {
        initComponents();
        
        //DESHABILITAR BOTON CERRAR
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
          public void windowClosing(WindowEvent e) {
            JOptionPane.showMessageDialog(null, "Usar el boton SALIR del menu inicio!", "AVISO",JOptionPane.INFORMATION_MESSAGE);
          }
        });           

        //Llamar metodo para agregar usuario a tabla
        Prestamo prestamos = new Prestamo();
        //Nombres de columnas
        String[] columnNames = {"ID", "Título", "Material", "Autor", "Número de Páginas", "Editorial", "ISBN", "Periodicidad", "Fecha de Pub.", "Artista", "Género", "Duración", "Número de canciones", "Director", "Disponibles"};

        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
        // The 0 argument is number rows.

        //JTable tblUsuarios = new JTable(tableModel);
        ArrayList<ArrayList<String>> objs = prestamos.mostrarMaterial();

        for (int i = 0; i < objs.size(); i++) {
            String id = objs.get(i).get(0);
            String titulo = objs.get(i).get(1);
            String material = objs.get(i).get(2);
            String autor = objs.get(i).get(3);
            String paginas = objs.get(i).get(4);
            String editorial = objs.get(i).get(5);
            String isbn = objs.get(i).get(6);
            String period = objs.get(i).get(7);
            String artista = objs.get(i).get(8);
            String genre = objs.get(i).get(9);
            String duracion = objs.get(i).get(10);
            String canciones = objs.get(i).get(11);
            String director = objs.get(i).get(12);
            String unidades = objs.get(i).get(13);

            Object[] data = {id, titulo, material, autor, paginas, editorial, isbn, period, artista, genre, duracion, canciones, director, unidades};
            tableModel.addRow(data);
        }
        //Llenar tabla
        tblMateriales.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVerUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMateriales = new javax.swing.JTable();
        btnPrestar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblNickname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlVerUser.setBackground(new java.awt.Color(0, 0, 51));
        pnlVerUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMateriales.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jScrollPane1.setViewportView(tblMateriales);

        pnlVerUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 650, 260));

        btnPrestar.setBackground(new java.awt.Color(0, 0, 204));
        btnPrestar.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestar.setText("Prestar");
        btnPrestar.setBorder(null);
        btnPrestar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });
        pnlVerUser.add(btnPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 80, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 51));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });
        pnlVerUser.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 80, 40));

        txtUsuario.setBackground(new java.awt.Color(0, 0, 51));
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setAlignmentX(0.8F);
        txtUsuario.setBorder(null);
        txtUsuario.setMargin(new java.awt.Insets(5, 15, 5, 5));
        txtUsuario.setMinimumSize(new java.awt.Dimension(5, 20));
        txtUsuario.setName("txtUsuario"); // NOI18N
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlVerUser.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 20));

        jSeparator6.setForeground(new java.awt.Color(102, 0, 204));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        pnlVerUser.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, -1));

        lblNickname.setBackground(new java.awt.Color(0, 0, 51));
        lblNickname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNickname.setForeground(new java.awt.Color(204, 204, 204));
        lblNickname.setText("Ingrese usuario:");
        pnlVerUser.add(lblNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVerUser, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlVerUser, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        try {
            //Variable para almacenar el valor de la fla seleccionada
            int fila = tblMateriales.getSelectedRow();

            String idMater = tblMateriales.getValueAt(fila, 0).toString();
            String usuario = txtUsuario.getText();
            int rolId = Globales.rolUsuario;

            //Condicionales
            if (!prestamos.existeMaterial(idMater)) {
                JOptionPane.showMessageDialog(this, "No existe ningún material con ese ID. \n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            } else if (usuario.equals("") || usuario == null) {
                JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", JOptionPane.ERROR_MESSAGE);
            }

            //Bloque de código para verificar si el socio existe en el sistema
            boolean aceptado = prestamos.existeUsuario(usuario);
            if (!aceptado) {
                JOptionPane.showMessageDialog(this, "No existe ningún usuario con ese documento. \n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                txtUsuario.setText("");
                txtUsuario.requestFocus();
            } else if (prestamos.verificarMora(usuario)) {
                JOptionPane.showMessageDialog(this, "El usuario " + usuario + " no puede realizar prestamo. \n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                int opcion = JOptionPane.showConfirmDialog(this, "" + usuario + "¿Desea cancelar la deuda?. \n", "CONFIRMAR", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(opcion==JOptionPane.YES_OPTION){
                    Pagar_Deuda deuda = new Pagar_Deuda();
                    deuda.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,"Deuda no cancelada. \n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                }
                txtUsuario.setText("");
            } else if (prestamos.verificarPrestamo(usuario, idMater)) {
                JOptionPane.showMessageDialog(this, "El usuario " + usuario + " ya cuenta con el material seleccionado. \n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                txtUsuario.setText("");
            } else if (!prestamos.materialDisp(idMater)) {
                JOptionPane.showMessageDialog(this, "No contamos con unidades de ese material. Intenta con otro \n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                txtUsuario.setText("");
                txtUsuario.requestFocus();
            }else {
                // Insertar el prestamo a la DB.
                prestamos.insertarPrestamo(usuario, idMater);
                JOptionPane.showMessageDialog(this, "¡Prestamo realizado exitosamente! \n", "HECHO", JOptionPane.INFORMATION_MESSAGE);
                txtUsuario.setText("");
                //mostrarMaterial();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila de la tabla. \n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        // TODO add your handling code here:
        Menu_Prestamos back = new Menu_Prestamos();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarMousePressed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestar_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestar_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestar_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestar_Material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Prestar_Material().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Prestar_Material.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JPanel pnlVerUser;
    private javax.swing.JTable tblMateriales;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
