/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import datos.Globales;
import datos.Usuario;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


public class Ver_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Ver Usuario
     */
    public Ver_Usuario() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Usuarios en sistema");
        
        //DESHABILITAR BOTON CERRAR
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
          public void windowClosing(WindowEvent e) {
            JOptionPane.showMessageDialog(null, "Usar el boton SALIR del menu inicio!", "AVISO",JOptionPane.INFORMATION_MESSAGE);
          }
        });           
        
        //Llamar metodo para agregar usuario a tabla
        Usuario usuarios = new Usuario();        
        //Nombres de columnas
        String[] columnNames = {"Id","Nombre","Apellido","Nickname", "Email", "Perfil", "F.Nacimiento", "Mora"};

        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
        // The 0 argument is number rows.

        //JTable tblUsuarios = new JTable(tableModel);
        
        ArrayList<ArrayList<String>> objs = usuarios.mostrarUsuarios();

       for (int i = 0; i < objs.size(); i++){
            String id = objs.get(i).get(0);
            String nombre = objs.get(i).get(1);
            String apellido = objs.get(i).get(2);
            String nickname = objs.get(i).get(3);
            String email = objs.get(i).get(4);
            String rol = objs.get(i).get(5);
            String fecha_nacimiento = objs.get(i).get(6);
            String mora = "$ "+ objs.get(i).get(7);
            
            Object[] data = {id,nombre,apellido,nickname,email,rol,fecha_nacimiento,mora};
            tableModel.addRow(data);
       }
        //Llenar tabla
        tblUsuarios.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVerUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlVerUser.setBackground(new java.awt.Color(0, 0, 51));
        pnlVerUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        pnlVerUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 690, 370));

        btnAtras.setBackground(new java.awt.Color(153, 0, 0));
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.setBorder(null);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAtrasMousePressed(evt);
            }
        });
        pnlVerUser.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 80, 40));

        btnModificar.setBackground(new java.awt.Color(0, 0, 204));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModificarMousePressed(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlVerUser.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 80, 40));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });
        pnlVerUser.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVerUser, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVerUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMousePressed
        // TODO add your handling code here:
        Menu_Usuarios users = new Menu_Usuarios();
        users.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasMousePressed

    private void btnModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMousePressed
        //verificamos si hay algun registro seleccionado, si no mostramos un error
        if(this.tblUsuarios.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null,"Debe seleccionar un registro para poder actualizar datos!");
        }
        else{
            try {
                //Seleccionamos numero de registro seleccionado
                int linea = this.tblUsuarios.getSelectedRow();
                int modelRow = tblUsuarios.convertRowIndexToModel(linea);
                String s = tblUsuarios.getModel().getValueAt(modelRow, 0)+"";

                EditarUser usr = new EditarUser(s);
                usr.setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Ver_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_btnModificarMousePressed

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        //Verificamos perfil usuario para saber si es administrador y puede actualizar datos
        Globales rolUsuario = new Globales();
        int idRol = rolUsuario.rolUsuario;
        //Evaluamos si es Administrador
        if(idRol == 1){
            //verificamos si hay algun registro seleccionado, si no mostramos un error
            if(this.tblUsuarios.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(null,"Debe seleccionar un registro para poder eliminarlo!");
            }
            else{
                try {
                    //Seleccionamos numero de registro seleccionado
                    int linea = this.tblUsuarios.getSelectedRow();
                    int modelRow = tblUsuarios.convertRowIndexToModel(linea);
                    String s = tblUsuarios.getModel().getValueAt(modelRow, 0)+"";
                    
                    //Mosstrar dialogo de confirmacion
                    JPanel panel = new JPanel();
                    panel.setSize(new Dimension(250, 100));
                    panel.setLayout(null);
                    JLabel label1 = new JLabel("Accion para borrar usuario de sistema");
                    label1.setVerticalAlignment(SwingConstants.BOTTOM);
                    label1.setBounds(20, 20, 200, 30);
                    label1.setHorizontalAlignment(SwingConstants.CENTER);
                    panel.add(label1);
                    JLabel label2 = new JLabel("Esta seguro de querer borrarlo?");
                    label2.setVerticalAlignment(SwingConstants.TOP);
                    label2.setHorizontalAlignment(SwingConstants.CENTER);
                    label2.setBounds(20, 80, 200, 20);
                    panel.add(label2);
                    UIManager.put("OptionPane.minimumSize", new Dimension(400, 200));
                    Icon icon;
                    int res = JOptionPane.showConfirmDialog(null, panel, "File",
                    JOptionPane.YES_NO_OPTION);
                    if(res == 0) {
                        //Eliminar usuario
                        Usuario usr = new Usuario();
                        usr.eliminarUsuario(s);
                    } else {
                        JOptionPane.showMessageDialog(null, "Acción cancelada!", "AVISO",JOptionPane.INFORMATION_MESSAGE);
                    }                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Ver_Usuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }        
        }else{
            JOptionPane.showMessageDialog(null,"Usted no posee permiso para modificar usuarios!");
        }
    }//GEN-LAST:event_btnEliminarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new Ver_Usuario();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlVerUser;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
